apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: db-admin-creds
spec:
  backend: env
  keys: [username, password]
---
apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: db-replication-creds
spec:
  backend: env
  keys: [username, password]
---
apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: lake-root-creds
spec:
  backend: env
  keys: [username, password]
