package compose

import (
	"fmt"
	"strings"
)

const apiVersion = "datascape.io/v1alpha1"

// provenanceComment is the exact comment ADR 024's "Quality bar" section
// specifies (parameterized by the command, e.g. "add pipeline").
func provenanceComment(command string) string {
	return fmt.Sprintf("# generated by platformctl %s; edit freely — files are the source of truth\n", command)
}

// renderDoc assembles one YAML document at blueprint quality: a provenance
// header, an optional multi-line explanatory comment, then
// apiVersion/kind/metadata.name/spec. specLines are written one level
// under spec: (2-space indented); callers nest further themselves for
// anything under spec.configuration/spec.postgres/etc. An empty specLines
// entry ("") renders as a blank line, for readability parity with the
// blueprint templates.
func renderDoc(command, explain, kind, name string, specLines []string) string {
	var b strings.Builder
	b.WriteString(provenanceComment(command))
	if explain != "" {
		for _, line := range strings.Split(strings.TrimRight(explain, "\n"), "\n") {
			if line == "" {
				b.WriteString("#\n")
			} else {
				b.WriteString("# " + line + "\n")
			}
		}
	}
	fmt.Fprintf(&b, "apiVersion: %s\n", apiVersion)
	fmt.Fprintf(&b, "kind: %s\n", kind)
	b.WriteString("metadata:\n")
	fmt.Fprintf(&b, "  name: %s\n", name)
	b.WriteString("spec:\n")
	for _, l := range specLines {
		if l == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("  " + l + "\n")
	}
	return b.String()
}

// renderMultiDoc joins several YAML documents with the "---" separator
// manifest.Load's multi-document decoder expects.
func renderMultiDoc(docs ...string) string {
	return strings.Join(docs, "---\n")
}

func refBlock(field, name string) []string {
	return []string{field + ":", "  name: " + name}
}

// flowList renders a flow-style YAML list, e.g. "[a, b, c]" — the same
// unquoted-scalar-list style the blueprint templates use for
// spec.secretRefs/options.tables.
func flowList(items []string) string {
	return "[" + strings.Join(items, ", ") + "]"
}
