apiVersion: datascape.io/v1alpha1
kind: Provider
metadata:
  name: local-postgres
spec:
  type: postgres
  runtime:
    type: docker
  configuration:
    version: "16"
    port: 15432
    superuserSecretRef: postgres-admin-creds
    replicationSecretRef: postgres-replication-creds
  secretRefs: [postgres-admin-creds, postgres-replication-creds]
