apiVersion: datascape.io/v1alpha1
kind: Provider
metadata:
  name: local-redpanda
spec:
  type: redpanda
  runtime:
    type: docker
    network: datascape
  configuration:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.1
