# network and image use their defaults (see README.md#defaults).
apiVersion: datascape.io/v1alpha1
kind: Provider
metadata:
  name: local-minio
spec:
  type: minio
  runtime:
    type: docker
  configuration:
    port: 19000
    rootSecretRef: minio-root-creds
  secretRefs: [minio-root-creds]
