apiVersion: datascape.io/v1alpha1
kind: Provider
metadata:
  name: local-minio
spec:
  type: minio
  runtime:
    type: docker
    network: datascape
  configuration:
    image: minio/minio:latest
    port: 19000
    rootSecretRef: minio-root-creds
  secretRefs: [minio-root-creds]
