# network and image use their defaults (see README.md#defaults).
apiVersion: datascape.io/v1alpha1
kind: Provider
metadata:
  name: local-redpanda
spec:
  type: redpanda
  runtime:
    type: docker
  configuration:
    kafkaPort: 19093
