apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: postgres-admin-creds
spec:
  backend: env
  keys: [username, password]
---
apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: postgres-replication-creds
spec:
  backend: env
  keys: [username, password]
---
apiVersion: datascape.io/v1alpha1
kind: SecretReference
metadata:
  name: minio-root-creds
spec:
  backend: env
  keys: [username, password]
